### ISSUE TITLE
Alex Binary gives me funny warnings window on Linux

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#32]
![latest-screenshot](https://user-images.githubusercontent.com/4953/91960688-811f7600-ed0a-11ea-96f8-777e9d619766.png)

**Comment by bettar** [comment]
Which Linux ?

**Comment by zdavatz** [comment]
Gentoo and Ubuntu.

**Comment by bettar** [comment]
Are you concerned about the error or the warning ? The error might be because you are running an application that hasn't been properly installed, in the sense that the expected auxiliary files are not there. About the warning, it needs to be investigated, strange that you get that warning in both Gentoo and Ubuntu.

**Comment by zdavatz** [comment]
No. Not worried.
