### ISSUE TITLE
Saving the same patient twice

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/amiko_linux#38]
![latest-screenshot](https://user-images.githubusercontent.com/4953/93430167-8829b500-f8c2-11ea-8d7e-010d8610b68d.png)

with this Screenshot I can not save 20.**05**.1975

![latest-screenshot](https://user-images.githubusercontent.com/4953/93430192-924bb380-f8c2-11ea-84c1-81fa740c8efa.png)

here it works.

related: https://github.com/zdavatz/amiko_linux/issues/26 and https://github.com/zdavatz/amiko_csharp/issues/81#issue-330573485

**Comment by zdavatz** [comment]
We need the Birthday-Format in Grey as on Mac, so the User knows how to enter the Birthday.

![latest-screenshot](https://user-images.githubusercontent.com/4953/93432291-99c08c00-f8c5-11ea-8f54-a0bbe3210d84.png)

**Comment by bettar** [comment]
Would it be better to have a "date picker" control there instead of the text control ?

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/93451533-9a621e00-f8d7-11ea-945d-f3e58e6e6b8f.png)

**Comment by bettar** [comment]
Yes, it is a problem that needs to be fixed. To understand what is going on, the same name could be inserted twice because the validation of the birthday string is not implemented yet. The birthday string is used in the calculation of the patient hash, so if once you enter "20.051975" and then "20.5.1975" event though they both refer to the same calendar day, the second string is not valid, and as I said, validation is not implemented yet.

**Comment by zdavatz** [comment]
Ok, to create a new patient you have to click on `+`. Currently you can not take an existing patient and change his name. You have to enter all values again, i.e. for a sister or brother.
