### ISSUE TITLE
Instruction on development

### ISSUE THREAD

**Issue by b123400** [zdavatz/amiko_linux#78]
I am trying to start development on this project, but I can't get started.
It seems like the project is managed by wxFormBuilder that I should not be editing some files manually.

https://github.com/zdavatz/amiko_linux/blob/1db326fcac16d22b9a3176806af7caa520db5521/gui/MainWindowBase.cpp#L5

I downloaded wxFormBuilder for both Linux and Mac, but both of them give the same error:

![image](https://user-images.githubusercontent.com/127193/98688198-f1531380-23ad-11eb-9d39-ae4a6b1d9c45.png)

I want to know:
- Which version of wxFormBuilder should I use?
- Which files should I (not) be editing?

**Comment by zdavatz** [comment]
Have you done these 4 steps: https://github.com/zdavatz/amiko_linux#setup

**Comment by zdavatz** [comment]
@bettar is not Developing on Linux, he is developing with Xcode and I am testing on Linux.

**Comment by zdavatz** [comment]
https://github.com/zdavatz/amiko_linux/blob/1db326fcac16d22b9a3176806af7caa520db5521/gui/MainWindowBase.cpp#L2-L5

**Comment by zdavatz** [comment]
@bettar says he built `wxFormBuilder` is from the latest sources. AFAICT the latest version is https://github.com/wxFormBuilder/wxFormBuilder 3.9.0, siehe: https://github.com/zdavatz/amiko_linux/blob/1db326fcac16d22b9a3176806af7caa520db5521/gui/MainWindowBase.cpp#L2 @bettar says this does not necessarily have to be correct. He will check and get back to us.

**Comment by b123400** [comment]
I downloaded prebuilt binary from the repo, it's also `3.9.0` but published on 26 Oct 2018.
They haven't make a new version for 2 years.
I will try to build from source.

**Comment by bettar** [comment]
You would use wxFormBuilder only when you want to make (some type of) changes to the GUI. Just to get started you don't need to do that, because all the files required to build the project are already in the git repository. In any case the wxFormBuilder version that I am using was built from sources on macOS, I think from git commit d053665 of 19 Aug 2020. The file wxFormBuilder.app shows version "3.5 RC2". When I launch it the title bar shows version "3.9.0". The saved .fbp files are version "1.15". The generated .cpp files show version "3.9.0". If you want to rebuild wxFormBuilder.app you might as well build it from the latest git commit of that project. I just rebuilt wxFormBuilder.app from the latest (commit 0eccdbc of 2 Nov 2020) sources and there are no differences in the files saved and created for this project.

**Comment by b123400** [comment]
I tried to build from the latest source (0eccdbc) and it worked. Thank you!
